package view;
import com.sap.db.jdbc.Driver;
import java.sql.*;
import java.util.ArrayList;

import javax.swing.JOptionPane;

import java.sql.CallableStatement;

public class connection {
String url="jdbc:sap://132.252.53.6:39015/?autocommit=false";
String user="BPSS1703";
String password="Han56%1!";
Connection conn;
//String driverName = "jdbc:sap://132.252.53.6:39015";
ArrayList<Coefficient> c1 = new ArrayList<Coefficient>();
ArrayList<Statics> s1 = new ArrayList<Statics>();
String aname="";

public Connection getconnection(long ean) 
{
	try {
	    conn = (Connection)DriverManager.getConnection(url,user,password);
			Statement s= conn.createStatement();
			ResultSet r=s.executeQuery("SELECT count(artikelbezeichnung) as anzahl,artikelbezeichnung from EDEKA1.BONS where EAN='"+ean+"' group by artikelbezeichnung");
			int count=0;
			while(r.next())
			{	
				if(count<r.getInt("anzahl")){
				aname=r.getString("artikelbezeichnung");
				count=r.getInt("anzahl");
				}
			}
			s.execute("SET SCHEMA BPSS1703");
			
			//s.execute("DROP TABLE #PAL_PARAMETER_TBL");
			String sql = "CREATE LOCAL TEMPORARY COLUMN TABLE #PAL_PARAMETER_TBL (PARAM_NAME VARCHAR(256), INT_VALUE INTEGER, DOUBLE_VALUE DOUBLE, STRING_VALUE VARCHAR(1000))"; 
             s.executeUpdate(sql);
			
            PreparedStatement p = conn.prepareStatement("INSERT INTO #PAL_PARAMETER_TBL VALUES ('POLYNOMIAL_NUM',3,NULL,NULL)");
            p.execute();
            System.out.println("Insert 1");
            PreparedStatement p1 = conn.prepareStatement("INSERT INTO #PAL_PARAMETER_TBL VALUES ('PMML_EXPORT',2,NULL,NULL)");
            p1.execute();
            System.out.println("Insert 2");
            s.execute("DROP TABLE PAL_PR_DATA_TBL");
        	String sql1 = "CREATE COLUMN TABLE PAL_PR_DATA_TBL ( ID INT GENERATED BY DEFAULT AS IDENTITY,Y DOUBLE,X1 DOUBLE)";
            s.executeUpdate(sql1);
            PreparedStatement p3 = conn.prepareStatement("INSERT INTO BPSS1703.PAL_PR_DATA_TBL (Y,X1) select sum(menge),t1.epreis from (select ean,menge,preis,preis/menge as epreis  from EDEKA1.BONS) as t1 where ean='"+ean+"' group by t1.epreis");
            p3.execute();
            System.out.println("Insert3");
           
            CallableStatement s1 = (CallableStatement) conn.prepareCall("CALL _SYS_AFL.PAL_POLYNOMIAL_REGRESSION(PAL_PR_DATA_TBL, '#PAL_PARAMETER_TBL', ?, ?, ?, ?,?)");
            boolean cst =s1.execute();
            int index =0;
            while (cst) {
            	index++;
                ResultSet rs = s1.getResultSet();
    			this.bearbeiteRes(rs,index);

                // process result set

                cst = s1.getMoreResults();
            }
            
			System.out.println("PrepareCall");
			Statement s2 = conn.createStatement();
            ResultSet d2 = s2.executeQuery("Select * from BPSS1703.PAL_PR_DATA_TBL;");
            //this.bearbeiteRes(d2);
            while (d2.next()){
            	System.out.println(d2.getDouble("y"));
            }

			conn.close();
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			JOptionPane.showMessageDialog(null,"Die EAN-Nr. existiert nicht!","Fehler",JOptionPane.ERROR_MESSAGE);
			e.printStackTrace();
			try {
				conn.close();
			} catch (SQLException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
		}
		
	
        System.out.println("Done");
        
        
        

	return conn;
}
	public void bearbeiteRes(ResultSet r1, int ind) throws SQLException{
		int anzahl = 0;
		while(r1.next()){
	      if (ind ==1){
	    	  Coefficient co1 = new Coefficient();
	    	  co1.coefID = r1.getDouble("COEFFICIENT_VALUE");
	    	  co1.coefname = r1.getString("VARIABLE_NAME");
	    	  c1.add(co1);
				anzahl ++;

	      }
	      
	      else if(ind ==4){
	    	    Statics st1  =new Statics();
	    	    st1.StatN = r1.getString("STAT_NAME");
	    	    st1.StatV = r1.getDouble("STAT_VALUE");
	    	    

 	    	    s1.add(st1);
				anzahl ++;

	      }
	      else
			anzahl ++;
//			System.out.println(r1.getDouble("COEFFICIENT_VALUE"));
//			System.out.println(r1.getString("VARIABLE_NAME"));
		}
		System.out.println("Anzahl:"+ anzahl);
	}
}



	

